### PR TITLE
fix doc example of setting a memcached entry

### PR DESCRIPTION
**Pull request by dbu**
according to the interfaces and to my testing, the lifetime comes before the options.

### CODE REVIEW

**Comment by mevdschee** [comment]
Good catch! Thank you very much.

**Comment by mevdschee** [comment]
See: http://git.php.net/?p=pecl/caching/memcache.git;a=blob;f=memcache.c;h=6a7576d1a86fdbeaf8f30c3cfd54ac642719c006;hb=HEAD#l2316

**Comment by dbu** [comment]
uh. is that memcache or memcached? but i am pretty conclusive that the
version i tested as well as the interfaces in the codegen folder
indicate the 3rd parameter really is the lifetime and not flags.

**Comment by mevdschee** [comment]
Ah.. yes, the older version that exposes the memcached object (not the memcache object) indeed had that order of parameters. The documentation has been adjusted to the new functionality (version 2 and up) and you must refer to the old functionality (version 1). I hope that clears things up. Nevertheless I would like to thank you for your participation, it is much appreciated!

**Pull request merged**
